# Workflow for processing and publishing bikeshed proposals to github pages

name: publish proposals
on:
  push:
    # only concerned with changes in the master branch
    branches: [ master ]
    # only invoke when a bikeshed document is updated
    # paths: [ '*.bs' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.2.0

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
    
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip
                    
      - name: install bikeshed
        run: |
          python3 -m pip install --upgrade bikeshed
          bikeshed update
          
      - name: generate html
        run: for index in proposals/*/index.bs; do bikeshed spec $index; done
          
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./proposals
          #publish_branch: master
          personal_token: ${{ secrets.GITHUB_TOKEN }} 
